{
 "title": "etcd 大盘",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "什么是 Etcd ?",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "etcd 是一个强一致性的分布式键值存储系统，为分布式系统或机器集群提供可靠的数据存储方式。它能够优雅地处理网络分区期间的领导者选举，并且可以容忍机器故障，即使在领导节点也是如此。\n"
   }
  },
  {
   "title": "副本存活数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(etcd_server_has_leader)", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "健康检查成功",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(etcd_server_health_success[1m]))"
    }
   ]
  },
  {
   "title": "今日 Leader 变化次数",
   "type": "graph",
   "description": "频繁的领导者变更会严重影响 etcd 的性能。这也意味着领导者不稳定，可能是由于网络连接问题或对 etcd 集群施加的过载负荷导致的。",
   "gridPos": { "h": 8, "w": 4, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "changes(etcd_server_leader_changes_seen_total[1d])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "失败的提案",
   "type": "graph",
   "description": "\n失败的提案通常与两个问题相关：与领导选举相关的暂时性故障或由于集群丧失法定人数而导致的较长时间的停机。",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(etcd_server_proposals_failed_total[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "pending 队列中的提案",
   "type": "stat",
   "description": "pending 的提案增加意味着存在较高的客户端负载或成员无法提交提案。",
   "gridPos": { "h": 7, "w": 3, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(etcd_server_proposals_pending)"
    }
   ]
  },
  {
   "title": "主节点",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "max(etcd_server_has_leader)" }
   ]
  },
  {
   "title": "检查失败",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(etcd_server_health_failures[1m]))",
     "legendFormat": "health_failures"
    },
    {
     "expr": "sum(increase(etcd_server_heartbeat_send_failures_total[1m]))",
     "legendFormat": "heartbeat_send_failures"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "MB" } },
   "yaxes": [
    { "format": "MB" }
   ],
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"kube-etcd\"}) by (instance) /1024/1024",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "打开文件描述符数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(process_open_fds{job=\"kube-etcd\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "提案情况",
   "type": "graph",
   "description": "如果集群正常运行，已提交的提案应该随着时间的推移而增加。重要的是要在集群的所有成员中监控这个指标；如果单个成员与其领导节点之间存在持续较大的滞后，这表明该成员运行缓慢或存在异常。",
   "gridPos": { "h": 8, "w": 5, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_server_proposals_committed_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "应用提案",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_server_proposals_applied_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "提案与应用的差值",
   "type": "timeseries",
   "description": "etcd 服务器会异步地应用每个已提交的提案。如果已提交的提案与已应用的提案之间的差异增加，这可能表明 etcd 服务器负载过重。",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "etcd_server_proposals_committed_total - etcd_server_proposals_applied_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "磁盘", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "db 大小",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_db_total_size_in_bytes",
     "legendFormat": "{{ instance }} 使用"
    },
    {
     "expr": "max(etcd_server_quota_backend_bytes)",
     "legendFormat": "限额"
    }
   ]
  },
  {
   "title": "磁盘操作延迟",
   "type": "graph",
   "description": "高磁盘操作延迟（wal_fsync_duration_seconds或backend_commit_duration_seconds）通常表示磁盘问题。它可能会导致高请求延迟或使群集不稳定。",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket[1m])) by (instance,le))",
     "legendFormat": "{{ instance }} WAL fsync "
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket[1m])) by (instance, le))",
     "legendFormat": "{{ instance }} 提案延迟"
    }
   ]
  },
  {
   "title": "快照持续时间",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 11, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_debugging_snap_save_total_duration_seconds_bucket[1m])) by (instance,le))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "网络", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "grpc客户端发送/接收",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_received_bytes_total[1m])",
     "legendFormat": "{{instance}} \t收到grpc客户端的总字节数"
    },
    {
     "expr": "rate(etcd_network_client_grpc_sent_bytes_total[1m])",
     "legendFormat": "{{instance}} \t发送grpc客户端的总字节数"
    }
   ]
  },
  {
   "title": "peer网络计算发送到特定对等方的总字节数",
   "type": "graph",
   "description": "peer_sent_bytes_total计算发送到特定对等方的总字节数。通常，领导成员发送的数据多于其他成员，因为它负责传输复制的数据。",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_sent_bytes_total[1m])) by (instance)",
     "legendFormat": "{{instance}} 发送总字节数"
    }
   ]
  },
  {
   "title": "peer计算从特定对等方接收的总字节数",
   "type": "graph",
   "description": "peer_received_bytes_total计算从特定对等方接收的总字节数。通常，关注成员仅从领导成员接收数据。",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_received_bytes_total[1m])) by (instance)",
     "legendFormat": "{{instance}} 接收总字节数"
    }
   ]
  },
  { "title": "Server请求", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "RPC Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{grpc_type=\"unary\"}[5m]))",
     "legendFormat": "RPC Rate"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_type=\"unary\",grpc_code!=\"OK\"}[5m]))",
     "legendFormat": "RPC Failed Rate"
    }
   ]
  },
  {
   "title": "实例请求分布",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{grpc_type=\"unary\"}[1m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "请求方法分布",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort(sum(rate(grpc_server_started_total{grpc_type=\"unary\"}[1m])) by (grpc_method))",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "请求类型分布",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort(sum(rate(grpc_server_started_total{grpc_type=\"unary\"}[1m])) by (grpc_service))",
     "legendFormat": "{{grpc_service}}"
    }
   ]
  },
  {
   "title": "实例请求失败",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_type=\"unary\",grpc_code!=\"OK\"}[1m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "请求错误状态码",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_type=\"unary\",grpc_code!=\"OK\"}[1m])) by (grpc_code)",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  },
  {
   "title": "请求方法失败",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_type=\"unary\",grpc_code!=\"OK\"}[1m])) by (grpc_method)",
     "legendFormat": "{{ grpc_method }}"
    }
   ]
  },
  {
   "title": "请求类型失败",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_type=\"unary\",grpc_code!=\"OK\"}[1m])) by (grpc_service)",
     "legendFormat": "{{grpc_service }}"
    }
   ]
  },
  {
   "title": "readindex慢查",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_server_slow_read_indexes_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ETCD请求延迟",
   "type": "graph",
   "description": "这里根据apiserver的监控接口",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_request_duration_seconds_bucket[1m])) by (instance,le))",
     "legendFormat": "{{ type }}"
    },
    {}
   ]
  }
 ]
}